### PR TITLE
Normalization fixes

### LINKED ISSUE #191: Entity names with underscores are treated inconsistently
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | unknown
| Version     | master

#### Summary

SOAP entities containing underscores are treated inconsistently in generated PHP code.

#### Current behavior

When generating PHP code, a SOAP entity with an underscore in the name will keep the underscore in some generated code, but will lose it in other generated code. The worst result of this is that the method calls generated using `generate:client` will have typehints that don't match the actual class names, causing them to be unusable.

#### How to reproduce

Create a config file with the following contents:

```
<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Rules;
use Phpro\SoapClient\CodeGenerator\Config\Config;

return Config::create()
    ->setWsdl('https://api.smdservers.net/CCWs_3.5/CallCenterWs.asmx?WSDL')
    ->setTypeDestination('src\Type')
    ->setTypeNamespace('Example')
    ->setClientDestination('src')
    ->setClientName('ExampleClient')
    ->setClientNamespace('Example')
    ->setClassMapDestination('src')
    ->setClassMapName('ExampleClassmap')
    ->setClassMapNamespace('Example')
    ->addRule(
        new Rules\AssembleRule(
            new Assembler\GetterAssembler(
                new Assembler\GetterAssemblerOptions()
            )
        )
    )
;
```

Run these commands:

```
vendor/bin/soap-client generate:classmap --config=config/soap-client.php
vendor/bin/soap-client generate:client --config=config/soap-client.php
vendor/bin/soap-client generate:types --config=config/soap-client.php
```

Using the `TenantUpdate_NationalAccount` entity as an example (and the associated Response and Result entities), we can see the following differences:

* The name of the result class in src/Type is `TenantUpdateNationalAccountResult`
* The member name and getter in `TenantUpdateNationalAccountResponse` uses `TenantUpdate_NationalAccountResult` instead
* The function in `CallCenterClient` has the name `tenantUpdate_NationalAccount` and has an invalid typehint (`TenantUpdate_NationalAccount`) and return type (`TenantUpdate_NationalAccountResponse`)

#### Expected behavior

The entity name is treated the same way in all generated code: it either keeps the underscore, or loses it.

### PR DESCRIPTION
**Pull request by veewee**
Fixes #192
Fixes #191

This PR contains:
- general type normalization written by @clamburger.
- improved client method naming suggested by @joshhornby.
- bugfix: use function name based on soap information instead of based on type.
- Rename valid soap method names that aren't valid in PHP.

### CODE REVIEW

**Comment by joshhornby** [comment]
Just tested this, and works perfectly!

**Comment by joshhornby** [comment]
@veewee Just tested this and not sure this is working quite yet. It fixes the docblocks, method name and type hint but not the return type. Please see the example below:

```
    /**
     * @param RequestInterface|Type\get_application_note $parameters
     * @param RequestInterface|Type\GetApplicationNote $parameters
     * @return ResultInterface|Type\get_application_noteResponse
     * @throws SoapException
     */
    public function get_application_note(\Foo\Bar\Type\get_application_note $parameters) : \Foo\Bar\Type\get_application_noteResponse
    public function getApplicationNote(\Foo\Bar\Type\GetApplicationNote $parameters) : \Foo\Bar\Type\get_application_noteResponse
    {
        return $this->call('get_application_note', $parameters);
    }
```

Notice `\Foo\Bar\Type\get_application_noteResponse` is still incorrect and should be `\Foo\Bar\Type\GetApplicationNoteResponse`

**Comment by veewee** [comment]
@joshhornby, Thanks for testing it out. I've fixed the remark.

**Comment by joshhornby** [comment]
@veewee Just re-tested and can confirm this works as expected. Great work.

File: src/Phpro/SoapClient/CodeGenerator/Util/Normalizer.php [hunk 1]
```diff
@@ -101,16 +101,17 @@ class Normalizer
 
     /**
      * @param string $name
+     * @param string $suffix
      *
      * @return string
      */
-    private static function normalizeReservedKeywords(string $name): string
+    private static function normalizeReservedKeywords(string $name, string $suffix): string
```
Comment (janvernieuwe) [inline src/Phpro/SoapClient/CodeGenerator/Util/Normalizer.php]: Wouldn't it be better to add the suffix where this is called?
