### PR TITLE
Don't replace underscores in class names to folders

### LINKED ISSUE #176: generate types to wrong directory
Hello,

WSDL: http://ws.ups.com.tr/wsCreateShipment/wsCreateShipment.asmx?WSDL

There is a type named "Login_Type1".

Login_Type1 generated BlaBla/Type/Login/Type1.php but class named "Login_Type1"

This brake PSR-4 autoloading.

Look at this codes;
$name = str_replace('_', DIRECTORY_SEPARATOR, $this->getName());

This code is in CodeGenerator/Model/Type.php line: 87 (V: 0.7.5)

Thanks.

### PR DESCRIPTION
**Pull request by janvernieuwe**
Fixes #176

### CODE REVIEW

File: spec/Phpro/SoapClient/CodeGenerator/Util/NormalizerSpec.php [hunk 1]
```diff
@@ -30,7 +30,7 @@ function it_can_normalize_namespace()
     function it_can_normalize_classnames()
     {
         $this->normalizeClassname('myType')->shouldReturn('MyType');
-        $this->normalizeClassname('my-./*type_123')->shouldReturn('Mytype_123');
+        $this->normalizeClassname('my-./*type_123')->shouldReturn('Mytype123');
```
Comment (irfanevrens) [inline spec/Phpro/SoapClient/CodeGenerator/Util/NormalizerSpec.php]: I thing "my-./*type_123" should return MyType123 not Mytype123

File: spec/Phpro/SoapClient/CodeGenerator/Model/TypeSpec.php [hunk 2]
```diff
@@ -50,10 +50,10 @@ function it_has_a_path_name()
         $this->getPathname('my/dir')->shouldReturn('my/dir/MyType.php');
     }
 
-    function it_should_replace_underscores_in_paths()
+    function it_should_not_replace_underscores_in_paths()
     {
         $this->beConstructedWith('MyNamespace', 'myType_3_2', ['prop1' => 'string']);
```
Comment (irfanevrens) [inline spec/Phpro/SoapClient/CodeGenerator/Model/TypeSpec.php]: Please try with "$this->beConstructedWith('MyNamespace', 'my_type_3_2', ['prop1' => 'string']);"
